name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create secrets
      run: |
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> ./local.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> ./local.properties
        echo "storeFilePath=${{ secrets.STORE_FILE_PATH }}" >> ./local.properties
        echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> ./local.properties

    - name: Build with Gradle
      run: ./gradlew build
